import { query } from "@anthropic-ai/claude-agent-sdk";
import { execSync, spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

export interface TriggerOptions {
  repo: string;
  prompt: string;
  worktree?: boolean;
  maxTurns?: number;
}

export interface TriggerResult {
  success: boolean;
  branch?: string;
  prUrl?: string;
  error?: string;
  numTurns?: number;
  totalCostUsd?: number;
}

const API_BASE = "http://localhost:4000";
const HOME = homedir();

function resolveRepoPath(repo: string): string {
  return join(HOME, "SourceRoot", repo);
}

function createWorktree(repoPath: string, branch: string): string {
  const worktreeDir = join(HOME, "SourceRoot", ".worktrees", branch);

  // Fetch latest before creating worktree
  execSync("git fetch origin", { cwd: repoPath, stdio: "pipe" });

  // Try to base off develop, fall back to main/master
  let base = "origin/develop";
  const result = spawnSync("git", ["rev-parse", "--verify", base], {
    cwd: repoPath,
    stdio: "pipe",
  });
  if (result.status !== 0) {
    const mainResult = spawnSync(
      "git",
      ["rev-parse", "--verify", "origin/main"],
      { cwd: repoPath, stdio: "pipe" }
    );
    base = mainResult.status === 0 ? "origin/main" : "origin/master";
  }

  execSync(`git worktree add "${worktreeDir}" -b "${branch}" ${base}`, {
    cwd: repoPath,
    stdio: "pipe",
  });

  return worktreeDir;
}

function removeWorktree(repoPath: string, worktreeDir: string): void {
  try {
    execSync(`git worktree remove "${worktreeDir}" --force`, {
      cwd: repoPath,
      stdio: "pipe",
    });
  } catch {
    // Non-fatal — worktree may already be gone
  }
}

async function sendNotification(
  message: string,
  title: string,
  priority = 3
): Promise<void> {
  try {
    await fetch(`${API_BASE}/api/notify`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ message, title, priority }),
    });
  } catch {
    // Non-fatal — notify failure shouldn't abort the run
  }
}

function createPr(
  cwd: string,
  branch: string,
  repo: string
): string | undefined {
  try {
    execSync(`git push origin "${branch}"`, { cwd, stdio: "pipe" });

    const result = spawnSync(
      "gh",
      [
        "pr",
        "create",
        "--base",
        "develop",
        "--title",
        `fix(agent): automated fix in ${repo}`,
        "--body",
        "Automated fix generated by headless Claude agent.",
      ],
      { cwd, encoding: "utf-8" }
    );

    if (result.status === 0) {
      return result.stdout.trim().split("\n").pop();
    }

    // develop branch not found — try main
    const mainResult = spawnSync(
      "gh",
      [
        "pr",
        "create",
        "--base",
        "main",
        "--title",
        `fix(agent): automated fix in ${repo}`,
        "--body",
        "Automated fix generated by headless Claude agent.",
      ],
      { cwd, encoding: "utf-8" }
    );

    return mainResult.status === 0
      ? mainResult.stdout.trim().split("\n").pop()
      : undefined;
  } catch {
    return undefined;
  }
}

export async function triggerAgent(
  options: TriggerOptions
): Promise<TriggerResult> {
  const { repo, prompt, worktree = true, maxTurns = 50 } = options;

  const repoPath = resolveRepoPath(repo);
  if (!existsSync(repoPath)) {
    return { success: false, error: `Repo not found: ${repoPath}` };
  }

  const branch = `fix/agent-${Date.now()}`;
  let cwd = repoPath;
  let worktreeDir: string | undefined;

  if (worktree) {
    try {
      worktreeDir = createWorktree(repoPath, branch);
      cwd = worktreeDir;
    } catch (err) {
      return {
        success: false,
        error: `Failed to create worktree: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }

  try {
    let numTurns = 0;
    let totalCostUsd = 0;
    let isError = false;
    let errors: string[] = [];

    for await (const message of query({
      prompt,
      options: {
        cwd,
        permissionMode: "bypassPermissions",
        allowDangerouslySkipPermissions: true,
        maxTurns,
      },
    })) {
      if (message.type === "result") {
        numTurns = message.num_turns;
        totalCostUsd = message.total_cost_usd;
        isError = message.is_error;
        if (message.subtype !== "success") {
          errors = message.errors;
        }
      }
    }

    if (isError) {
      await sendNotification(
        `Agent run failed in ${repo}: ${errors.join(", ")}`,
        repo,
        4
      );
      return { success: false, error: errors.join(", "), numTurns };
    }

    // Push branch and create PR
    const prUrl = createPr(cwd, branch, repo);

    const notifyMsg = prUrl
      ? `Agent run complete in ${repo}. PR: ${prUrl}`
      : `Agent run complete in ${repo}. Branch: ${branch} (no PR created)`;

    await sendNotification(notifyMsg, repo);

    return { success: true, branch, prUrl, numTurns, totalCostUsd };
  } finally {
    if (worktreeDir) {
      removeWorktree(repoPath, worktreeDir);
    }
  }
}

// CLI entrypoint — called by spawn-headless.sh via: bun run src/trigger-handler.ts --repo <r> --prompt <p> --worktree <bool>
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const get = (flag: string): string | undefined => {
    const idx = args.indexOf(flag);
    return idx !== -1 ? args[idx + 1] : undefined;
  };

  const repo = get("--repo");
  const prompt = get("--prompt");
  const worktreeArg = get("--worktree");

  if (!repo || !prompt) {
    console.error("Usage: trigger-handler.ts --repo <repo> --prompt <prompt> [--worktree true|false]");
    process.exit(1);
  }

  const result = await triggerAgent({
    repo,
    prompt,
    worktree: worktreeArg !== "false",
  });

  console.log(JSON.stringify(result, null, 2));
  process.exit(result.success ? 0 : 1);
}
